#!/bin/bash

ktfmtVersion=0.46
filename=ktfmt-$ktfmtVersion-jar-with-dependencies.jar
dir=~/.ktfmt
file=$dir/$filename
if ! test -f "$file"; then
    mkdir -p $dir
    curl -L https://search.maven.org/remotecontent?filepath=com/facebook/ktfmt/$ktfmtVersion/$filename -o $file
fi

echo ~~~ ktfmt $ktfmtVersion ~~~

start_time=$(gdate +%s%N | cut -b1-13)

# Capture the list of files to format and count them, avoiding to traverse node_modules directories
files=$(find . -type d -name node_modules -prune -false -o \( -name '*.kt' -o -name '*.kts' \))

# prepare command to format code
command="java -jar $file --dropbox-style $files"

# run command, display output, and extract errors
errors=$($command 2>&1 | tee /dev/tty | grep ' error: ')

end_time=$(gdate +%s%N | cut -b1-13)
echo "Time elapsed: $((end_time - start_time))ms"

# display errors at end (if any)
if [ -n "$errors" ]; then
    echo -e "\033[31mErrors detected:\n$errors\033[0m"
fi
