app.url:
#---------------------------------------------------------------------------
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
database:
  host:
  port: 0
  name: templatesample
  user: test
  password: test
  protocol: jdbc:tc:postgresql:15
#---------------------------------------------------------------------------
assets:
  useBuildFiles: false
  webpackDevPort:
  webpackDevHost:
#---------------------------------------------------------------------------
mailing:
  devDestination: dev+log-template-sample@example.com
  devLogSender: dev+log-template-sample@example.com
#---------------------------------------------------------------------------
