# TODO[tmpl][config] no / in urls end ?
# configuration validation
app.url: http://kttswebapptemplate:8123
#---------------------------------------------------------------------------
insertInitialData: true
#---------------------------------------------------------------------------
server.port: 8123
database:
  host: localhost
  port: 5432
  name: templatesample
  user: ${USER}
  password:
#---------------------------------------------------------------------------
assets:
  useBuildFiles: false
  webpackDevPort: 3123
  webpackDevHost: localhost
#---------------------------------------------------------------------------
mailjet:
  api-key:
  secret-key:
#---------------------------------------------------------------------------
remote-endpoint:
  expected-secu: remote-secu
#---------------------------------------------------------------------------
