context.initializer.classes: com.kttswebapptemplate.config.ApplicationBeans
spring:
  main.banner-mode: off
  jooq.sql-dialect: Postgres
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${database.protocol}://${database.host}:${database.port}/${database.name}
    username: ${database.user}
    password: ${database.password}
  freemarker:
    expose-request-attributes: true
    settings:
      template_exception_handler: rethrow
server:
  port: 8080
  error.whitelabel.enabled: true
  forward-headers-strategy: none
#---------------------------------------------------------------------------
insertInitialData: false
#---------------------------------------------------------------------------
mail:
  devLogSender: dev+log-template-sample@example.com
  devDestination: dev+log-template-sample@example.com
#---------------------------------------------------------------------------
assets.webpackDevHost:
#---------------------------------------------------------------------------
