app.url:
#---------------------------------------------------------------------------
database:
  host: localhost
  port: 5432
  name: templatesample-test
  user: mlo
  password:
#---------------------------------------------------------------------------
assets:
  useBuildFiles: false
  webpackDevPort:
  webpackDevHost:
#---------------------------------------------------------------------------
mailjet:
  apiKey:
  secretKey:
#---------------------------------------------------------------------------
remoteController:
  expectedSecu: remote-secu
#---------------------------------------------------------------------------
