# TODO[tmpl][config] no / in urls end ?
# configuration validation
app.url: http://devkttswebapptemplate:8123
#---------------------------------------------------------------------------
insertInitialData: true
#---------------------------------------------------------------------------
server.port: 8123
database:
  host: localhost
  port: 5432
  name: templatesample
  user: ${USER}
  password:
  protocol: jdbc:postgresql
#---------------------------------------------------------------------------
assets:
  useBuildFiles: false
  webpackDevPort: 3123
  webpackDevHost: localhost
#---------------------------------------------------------------------------
mailing:
  devDestination: ${DEV_MAIL:dev+log-template-sample@example.com}
#---------------------------------------------------------------------------
